---
# tasks file for K8S-Worker

- name: "Installing Docker"
  package:
          name: docker
          state: present

- name: "Start Docker Service with permanently enable"
  service:
          name: docker
          state: started
          enabled: yes

- name: "Configured Yum Repo for K8S"
  blockinfile:
    create: yes
    path: /etc/yum.repos.d/kubernetes.repo
    block: |
            [kubernetes]
            name=Kubernetes
            baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
            enabled=1
            gpgcheck=1
            repo_gpgcheck=1
            gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
            exclude=kubelet kubeadm kubectl

- name: "Installing kubelet,kubeadm,kubectl"
  shell: yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes

- name: "Start kubelet service with permanently enable"
  service:
          name: kubelet
          state: started
          enabled: yes

- name: "Changing CGROUP Driver"
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"]
      }

- name: "Restart Docker Service"
  service:
          name: docker
          state: restarted

- name: "Install ip-route-c"
  package:
          name: iproute-tc
          state: present

- name: "Set IP Tables"
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1

- name: "Starting sysctl"
  shell: sysctl --system

- name: "Token File"
  shell: "{{ token }}"
